backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "candidates"
    label: "Candidates"
    folder: "src/pages/candidates"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "candidate-fragment"}
      - {label: "First Name", name: "firstName", widget: "string"}
      - {label: "Last Name", name: "lastName", widget: "string"}
      - {label: "District", name: "district", widget: "string"}
      - {label: "State", name: "state", widget: "string"}
      - {label: "Election Date", name: "electionDate", widget: "date"}
      - {label: "Election Type", name: "electionType", widget: "select", options: ["fake", "primary", "general"]}
      - {label: "Office", name: "electionType", widget: "select", options: ["governor", "house", "senate"]}
      - {label: "Incumbent", name: "incumbent", widget: "boolean"}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Donation Link", name: "donationLink", widget: "string"}
      - {label: "Outcome", name: "outcome", widget: "select", options: ["Won", "Lost", "Unknown"]}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Blurb", name: "blurb", widget: "text"}

  - name: "issues"
    label: "Issues"
    folder: "src/pages/issues"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "issue-fragment"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Icon", name: "icon", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/issue-pages/index.md"
        label: "Issues"
        name: "issues"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "issue-fragment"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Text", name: "bannerText", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Sub Header", name: "subheader", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}


      - file: "src/pages/landing/index.md"
        label: "Landing"
        name: "landing"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "landing-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Background Image", name: "bannerBackgroundImg", widget: "image"}
          - {label: "Banner Text Image", name: "bannerTextImg", widget: "image"}
          - {label: "Bold Header", name: "boldHeader", widget: "string"}
          - {label: "Bold Subheader", name: "boldSubheader", widget: "string"}
          - {label: "Intro Content", name: "introContent", widget: "markdown"}
          - {label: "First Call Out Icon", name: "firstCalloutIcon", widget: "image"}
          - {label: "First Call Out Text", name: "firstCalloutText", widget: "text"}
          - {label: "Issues Introduction", name: "issuesIntro", widget: "string"}

          - label: "Primary Issues"
            name: "primaryIssues"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Url", name: "url", widget: "string"}
          
          - {label: "JD Highlight Header", name: "jdHighlightHeader", widget: "string"}
          - {label: "JD Highlight Text", name: "jdHighlightText", widget: "text"}
          - {label: "JD Highlight Icon", name: "jdHighlightIcon", widget: "image"}

          - label: "Blocks"
            name: "blocks"
            widget: list
            fields:
              - {label: "Banner Image", name: "bannerImageUrl", widget: "image"}
              - {label: "Banner Text", name: "bannerText", widget: "string"}
              - {label: "Banner Button Text", name: "bannerButtonText", widget: "string"}
              - {label: "Banner Button Url", name: "bannerButtonUrl", widget: "string"}
              - {label: "Alignment", name: "alignment", widget: "string"}
              - {label: "Content Header", name: "header", widget: "string"}
              - {label: "Content Sub-Header", name: "subheader", widget: "string"}
              - {label: "Content", name: "htmlContent", widget: "markdown"}
              - {label: "More Button Text", name: "moreButtonText", widget: "string"}
              - {label: "More Button Url", name: "moreButtonUrl", widget: "string"}
              - {label: "Call Out Icon", name: "calloutIcon", widget: "image"}
              - {label: "Call Out Text", name: "calloutText", widget: "text"}